"""empty message

Revision ID: 188f3bcf4e6e
Revises: a9a70a700d77
Create Date: 2018-05-16 10:37:21.380440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188f3bcf4e6e'
down_revision = 'a9a70a700d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'article', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'article_tags', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'article_tags', 'article', ['article_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'article', ['article_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'article_tags', type_='foreignkey')
    op.drop_constraint(None, 'article_tags', type_='foreignkey')
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_constraint(None, 'article', type_='foreignkey')
    # ### end Alembic commands ###
