"""empty message

Revision ID: 888519375955
Revises: 188f3bcf4e6e
Create Date: 2018-05-16 14:31:21.686510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '888519375955'
down_revision = '188f3bcf4e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article', 'category', ['category_id'], ['id'])
    op.drop_column('article', 'tag_id')
    op.create_foreign_key(None, 'article_tags', 'article', ['article_id'], ['id'])
    op.create_foreign_key(None, 'article_tags', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'article', ['article_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'article_tags', type_='foreignkey')
    op.drop_constraint(None, 'article_tags', type_='foreignkey')
    op.add_column('article', sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'article', type_='foreignkey')
    # ### end Alembic commands ###
