"""empty message

Revision ID: a9a70a700d77
Revises: a251532178e9
Create Date: 2018-05-16 10:36:16.292394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a70a700d77'
down_revision = 'a251532178e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('descript', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'article', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'article', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'article_tags', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'article_tags', 'article', ['article_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'article', ['article_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'article_tags', type_='foreignkey')
    op.drop_constraint(None, 'article_tags', type_='foreignkey')
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'descript')
    # ### end Alembic commands ###
